# pull official base image
FROM postgres:13-alpine

RUN mkdir sql_files
ADD ./sql_files/* /sql_files

# add initialization shell script to the docker entrypoint
ADD initialize_database.sh /docker-entrypoint-initdb.d

